// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTpCXYxSdIokqzSnnzsi4sXo32eFzW3Co',
    appId: '1:730508018952:web:d7ae5dea3a44a1f6a958bd',
    messagingSenderId: '730508018952',
    projectId: 'ruang-les-ismaturrohmah',
    authDomain: 'ruang-les-ismaturrohmah.firebaseapp.com',
    storageBucket: 'ruang-les-ismaturrohmah.firebasestorage.app',
    measurementId: 'G-C7TRX7YSTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAN79Dk_aF55IRJPFf3jLmXyCFnJZgmvI',
    appId: '1:730508018952:android:5d55368876b4e108a958bd',
    messagingSenderId: '730508018952',
    projectId: 'ruang-les-ismaturrohmah',
    storageBucket: 'ruang-les-ismaturrohmah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4zy3v0_Nb89LChSR1sAU2p7j_xQdPJTU',
    appId: '1:730508018952:ios:4e203d36481c9619a958bd',
    messagingSenderId: '730508018952',
    projectId: 'ruang-les-ismaturrohmah',
    storageBucket: 'ruang-les-ismaturrohmah.firebasestorage.app',
    iosBundleId: 'com.example.proyekRuangles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4zy3v0_Nb89LChSR1sAU2p7j_xQdPJTU',
    appId: '1:730508018952:ios:4e203d36481c9619a958bd',
    messagingSenderId: '730508018952',
    projectId: 'ruang-les-ismaturrohmah',
    storageBucket: 'ruang-les-ismaturrohmah.firebasestorage.app',
    iosBundleId: 'com.example.proyekRuangles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTpCXYxSdIokqzSnnzsi4sXo32eFzW3Co',
    appId: '1:730508018952:web:fe6bd4aefb6ba8c2a958bd',
    messagingSenderId: '730508018952',
    projectId: 'ruang-les-ismaturrohmah',
    authDomain: 'ruang-les-ismaturrohmah.firebaseapp.com',
    storageBucket: 'ruang-les-ismaturrohmah.firebasestorage.app',
    measurementId: 'G-XV4J07SYC7',
  );
}
